version: '3'

dotenv:
  - .env

tasks:
  build:
    dir: src
    cmds:
      - idf.py build

  flash:
    dir: src
    cmds:
      - idf.py -p {{.DEFAULT_PORT}} flash

  monitor:
    dir: src
    cmds:
      - idf.py -p {{.DEFAULT_PORT}} monitor

  run:
    cmds:
      - task: flash
      - task: monitor

  dev:
    cmds:
      - task: build
      - task: run
